/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VacinacaoRouteImport } from './routes/vacinacao'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as InternacaoRouteImport } from './routes/internacao'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ConsultasRouteImport } from './routes/consultas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AniversariosRouteImport } from './routes/aniversarios'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VacinacaoRoute = VacinacaoRouteImport.update({
  id: '/vacinacao',
  path: '/vacinacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const InternacaoRoute = InternacaoRouteImport.update({
  id: '/internacao',
  path: '/internacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultasRoute = ConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AniversariosRoute = AniversariosRouteImport.update({
  id: '/aniversarios',
  path: '/aniversarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/aniversarios': typeof AniversariosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consultas': typeof ConsultasRoute
  '/financeiro': typeof FinanceiroRoute
  '/internacao': typeof InternacaoRoute
  '/mensagens': typeof MensagensRoute
  '/pets': typeof PetsRoute
  '/produtos': typeof ProdutosRoute
  '/vacinacao': typeof VacinacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/aniversarios': typeof AniversariosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consultas': typeof ConsultasRoute
  '/financeiro': typeof FinanceiroRoute
  '/internacao': typeof InternacaoRoute
  '/mensagens': typeof MensagensRoute
  '/pets': typeof PetsRoute
  '/produtos': typeof ProdutosRoute
  '/vacinacao': typeof VacinacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/aniversarios': typeof AniversariosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consultas': typeof ConsultasRoute
  '/financeiro': typeof FinanceiroRoute
  '/internacao': typeof InternacaoRoute
  '/mensagens': typeof MensagensRoute
  '/pets': typeof PetsRoute
  '/produtos': typeof ProdutosRoute
  '/vacinacao': typeof VacinacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/aniversarios'
    | '/clientes'
    | '/configuracoes'
    | '/consultas'
    | '/financeiro'
    | '/internacao'
    | '/mensagens'
    | '/pets'
    | '/produtos'
    | '/vacinacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/aniversarios'
    | '/clientes'
    | '/configuracoes'
    | '/consultas'
    | '/financeiro'
    | '/internacao'
    | '/mensagens'
    | '/pets'
    | '/produtos'
    | '/vacinacao'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/aniversarios'
    | '/clientes'
    | '/configuracoes'
    | '/consultas'
    | '/financeiro'
    | '/internacao'
    | '/mensagens'
    | '/pets'
    | '/produtos'
    | '/vacinacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  AniversariosRoute: typeof AniversariosRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConsultasRoute: typeof ConsultasRoute
  FinanceiroRoute: typeof FinanceiroRoute
  InternacaoRoute: typeof InternacaoRoute
  MensagensRoute: typeof MensagensRoute
  PetsRoute: typeof PetsRoute
  ProdutosRoute: typeof ProdutosRoute
  VacinacaoRoute: typeof VacinacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vacinacao': {
      id: '/vacinacao'
      path: '/vacinacao'
      fullPath: '/vacinacao'
      preLoaderRoute: typeof VacinacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internacao': {
      id: '/internacao'
      path: '/internacao'
      fullPath: '/internacao'
      preLoaderRoute: typeof InternacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultas': {
      id: '/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof ConsultasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aniversarios': {
      id: '/aniversarios'
      path: '/aniversarios'
      fullPath: '/aniversarios'
      preLoaderRoute: typeof AniversariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  AniversariosRoute: AniversariosRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConsultasRoute: ConsultasRoute,
  FinanceiroRoute: FinanceiroRoute,
  InternacaoRoute: InternacaoRoute,
  MensagensRoute: MensagensRoute,
  PetsRoute: PetsRoute,
  ProdutosRoute: ProdutosRoute,
  VacinacaoRoute: VacinacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
